### ISSUE TITLE
Branch doesn't match with actual version

### ISSUE THREAD

**Issue by Elikill58** [CodedRed-Spigot/MoneyNote#5]
The current update on spigot is not on any branch of this repository. It's not possible to fork or edit it.
Even if I know that you want to re-code it, is it possible to get a backup of the actual code ? It's to use my own eco system instead of vault one.

**Comment by CodedRedGIT** [comment]
The old code is not on Github because it does not work with 1.18 at all. This github repo will eventually become the 1.18 version.

**Comment by Elikill58** [comment]
Yes but it works with 1.17 and lower, so it's quite sad to don't have a save of old working version for old MC
